BEGIN;
-- DROP TABLES (drop in dependency order)
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS shopping_cart_items CASCADE;
DROP TABLE IF EXISTS routine_steps CASCADE;
DROP TABLE IF EXISTS routines CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

-- CREATE TABLES (in order so referenced tables exist first)

-- CATEGORIES TABLE
CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT NULL, -- parent category
    name VARCHAR(100) NOT NULL,
    CONSTRAINT fk_category_parent FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- PRODUCTS TABLE
CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INT NULL,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(10,2) NOT NULL,
    stock_quantity INT NOT NULL,
    image_url VARCHAR(255),
    alt_text VARCHAR(255),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- USERS TABLE
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone BIGINT
);

-- ADDRESSES TABLE
CREATE TABLE addresses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    address_type VARCHAR(20) CHECK (address_type IN ('shipping', 'billing')),
    CONSTRAINT fk_user_address FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- SHOPPING_CART_ITEMS TABLE
CREATE TABLE shopping_cart_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,
    CONSTRAINT cart_unique UNIQUE (user_id, product_id) -- ensure one entry per product per user this is new and not updated
);

-- ORDERS TABLE
CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    order_date TIMESTAMP DEFAULT NOW(),
    status VARCHAR(50) NOT NULL CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    shipping_address_id INT,
    billing_address_id INT,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_shipping_address FOREIGN KEY (shipping_address_id)
        REFERENCES addresses(id),
    CONSTRAINT fk_orders_billing_address FOREIGN KEY (billing_address_id)
        REFERENCES addresses(id)
);

-- ORDER_ITEMS TABLE (product_id is nullable to allow ON DELETE SET NULL)
CREATE TABLE order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE SET NULL
);

-- PAYMENTS TABLE
CREATE TABLE payments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    payment_method VARCHAR(50) NOT NULL CHECK (
        payment_method IN ('credit_card', 'paypal', 'stripe', 'bank_transfer', 'cash')
    ),
    amount NUMERIC(10,2) NOT NULL,
    status VARCHAR(50) NOT NULL CHECK (
        status IN ('pending', 'completed', 'failed', 'refunded')
    ),
    transaction_reference VARCHAR(255),
    transaction_time TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_payment_order FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE
);

-- ROUTINES TABLE
CREATE TABLE routines (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT fk_routine_user FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ROUTINE_STEPS TABLE (product_id is nullable to allow ON DELETE SET NULL)
CREATE TABLE routine_steps (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id INT NOT NULL,
    step_number INT NOT NULL,
    product_id INT NULL,
    instructions VARCHAR(1000),
    CONSTRAINT fk_routinesteps_routine FOREIGN KEY (routine_id)
        REFERENCES routines(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_routinesteps_product FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE SET NULL
);
COMMIT;